<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>plugin</artifactId>
        <version>2.36</version>
        <relativePath />
    </parent>
    <artifactId>nodepool-agents</artifactId>
    <version>0.0.22-SNAPSHOT</version>
    <packaging>hpi</packaging>
    <properties>
        <!-- Original -->
        <!--<jenkins.version>2.73.3</jenkins.version>-->
        <!-- Jenkins -->
        <!--<jenkins.version>2.107.1</jenkins.version>-->
        <!-- Jenkins version bump to support BlueOcean -->
        <!-- <jenkins.version>2.107.3</jenkins.version> -->
        <!-- Currently the Latest and Greatest -->
        <jenkins.version>2.138.3</jenkins.version>
        <java.level>8</java.level>
    </properties>
    <name>NodePool Agents Plugin</name>
    <description>Allows user to build on NodePool controlled cloud instances</description>
    <url>https://wiki.jenkins.io/display/JENKINS/NodePool+Agents+Plugin</url>
    <!-- The default licence for Jenkins OSS Plugins is MIT. Substitute for the applicable one if needed. -->
    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://opensource.org/licenses/MIT</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>hsaunders</id>
            <name>Hugh Saunders</name>
            <email>hugh.saunders@rackspace.com</email>
        </developer>
        <developer>
            <id>bdelliott</id>
            <name>Brian D. Elliott</name>
            <email>brian.elliott@rackspace.com</email>
        </developer>
        <developer>
            <id>ddeal</id>
            <name>David Deal</name>
            <email>david.deal@rackspace.com</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/jenkinsci/${project.artifactId}-plugin.git</connection>
        <developerConnection>scm:git:git@github.com:jenkinsci/${project.artifactId}-plugin.git</developerConnection>
        <url>https://github.com/jenkinsci/${project.artifactId}-plugin</url>
        <tag>HEAD</tag>
    </scm>

    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <name>Jenkins Repository</name>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
        <repository>
            <id>central</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>bintray-palantir-maven</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/palantir/maven</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jenkins-ci.tools</groupId>
                <artifactId>maven-hpi-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <showDeprecation>true</showDeprecation>
                    <webApp>
                        <contextPath>/jenkins</contextPath>
                    </webApp>
                    <!-- See: https://jenkinsci.github.io/maven-hpi-plugin/run-mojo.html -->
                    <loggers>
                        <com.rackspace>ALL</com.rackspace>
                        <org.apache.zookeeper>WARNING</org.apache.zookeeper>
                        <org.apache.curator>WARNING</org.apache.curator>
                        <org.springframework.beans>WARNING</org.springframework.beans>
                        <org.jenkinsci.plugins>WARNING</org.jenkinsci.plugins>
                    </loggers>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.4.10.v20180503</version>
                <configuration>
                    <scanIntervalSeconds>10</scanIntervalSeconds>
                    <webApp>
                        <contextPath>/jenkins</contextPath>
                    </webApp>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.0-alpha-2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>set-system-properties</goal>
                        </goals>
                        <configuration>
                            <properties>
                                <property>
                                    <name>java.util.logging.SimpleFormatter.format</name>
                                    <!-- See: https://docs.oracle.com/javase/7/docs/api/java/util/logging/SimpleFormatter.html for columns -->
                                    <!-- Shows Logger name and method: %2 -->
                                    <!--<value>[%4$6.6s][%1$tY-%1$tm-%1$tdT%1$tH:%1$tM:%1$tS%tz] %2$s %5$s%6$s%n</value> -->
                                    <!-- Show Logger name only (doesn't include the method): %3 -->
                                    <value>[%4$6.6s][%1$tY-%1$tm-%1$tdT%1$tH:%1$tM:%1$tS%tz] %3$s - %5$s%6$s%n</value>
                                </property>
                            </properties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
                <configuration>
                    <systemPropertyVariables>
                        <log4j.configuration>file:${basedir}/src/test/resources/log4j.properties</log4j.configuration>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.2</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>cloud-stats</artifactId>
            <version>0.9</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>4.0.1</version>
            <!-- curator 4 has a maven dep on zk3.5, but also has a
                 compatibility mode for zk3.4. In order to use zk3.4, the
                 maven dep on 3.5 must be excluded, and a dep on zk3.4 added
                 see: https://curator.apache.org/zk-compatibility.html
            -->
            <exclusions>
                <exclusion>
                    <groupId>org.apache.zookeeper</groupId>
                    <artifactId>zookeeper</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.4.11</version>
            <exclusions>
                <exclusion>
                    <groupId>jline</groupId>
                    <artifactId>jline</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-test</artifactId>
            <version>2.12.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.zookeeper</groupId>
                    <artifactId>zookeeper</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>docker-java-api</artifactId>
            <version>3.7.0-133.v2a_9174cd5822</version>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>2.15.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-job</artifactId>
            <version>2.25</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>ssh-slaves</artifactId>
            <version>1.29.1</version>
        </dependency>
        <!-- Required for newer Jenkins as hudson.plugins.sshslaves.SFTPClient was removed from ssh-slaves -->
        <!-- This dependency pulls in trilead-ssh2 which provides the SSH2 library/protocol in Java -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>trilead-api</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>structs</artifactId>
            <version>1.14</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>scm-api</artifactId>
            <version>2.2.6</version>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>credentials</artifactId>
            <version>2.1.18</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-aggregator</artifactId>
            <version>2.5</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>ssh-credentials</artifactId>
            <version>1.14</version>
        </dependency>
        <dependency>
            <!-- CommandLauncher was detached from core some time ago (cf. https://github.com/jenkinsci/jenkins/pull/3076) -->
            <!-- Needed for running the unit tests for more recent versions of Jenkins -->
            <!-- Some discussion here: https://groups.google.com/forum/#!topic/jenkinsci-dev/OJ7JadgPUzE -->
            <groupId>${project.groupId}</groupId>
            <artifactId>command-launcher</artifactId>
            <version>1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>script-security</artifactId>
            <version>1.39</version>
            <scope>test</scope>
        </dependency>
        <!-- If Jenkins >= 2.112 - avoids java.lang.NoClassDefFoundError: hudson/tools/JDKInstaller$FileSystem -->
        <!--<dependency>-->
            <!--<groupId>${project.groupId}</groupId>-->
            <!--<artifactId>jdk-tool</artifactId>-->
            <!--<version>1.1</version>-->
            <!--<scope>test</scope>-->
        <!--</dependency>-->
    </dependencies>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.5</version>
            </plugin>
        </plugins>
    </reporting>
</project>
